[package]
name = "reperm_gen"
version = "0.1.0"
edition = "2021"

[dependencies]
bimap = "0.6.3"
clap = { version = "4.5.13", features = ["derive"] }
permutohedron = "0.2.4"
petgraph = "0.6.4"
rayon = "1.10.0"
serde = { version = "1.0.204", features = ["derive"] }
tracing = "0.1.40"
